[build-system]

requires = [
    "setuptools",
    "setuptools_scm",
    "wheel",
    "scikit-build",
    "cmake",
    "ninja",
    "ecl",
    "conan",
    "pybind11>=2.8.1",  # If this comes out of sync with the version installed by Conan please update the version in CMakeLists
    "grpcio-tools",
]


[tool.pytest.ini_options]
addopts = "-ra --strict-markers"
markers = [
    "consumer_driven_contract_test",
    "consumer_driven_contract_verification",
    "ert3",
    "integration_test",
    "quick_only",
    "requires_eclipse",
    "requires_ert_storage",
    "requires_window_manager",
    "script",
    "slow",
    "unstable",
]
log_cli = "false"
asyncio_mode = "auto"
